In [1]:
import pandas as pd
from matplotlib import font_manager, rc
font_path = 'C:/Windows/Fonts/NanumGothic.ttf'
font_name = font_manager.FontProperties(fname=font_path).get_name()

In [2]:
df_train = pd.read_csv("../review/open/train.csv")
df_test = pd.read_csv("../review/open/test.csv")

In [3]:
df_train.head()

,ID,사고일시,요일,기상상태,시군구,도로형태,노면상태,사고유형,사고유형 - 세부분류,법규위반,...,가해운전자 상해정도,피해운전자 차종,피해운전자 성별,피해운전자 연령,피해운전자 상해정도,사망자수,중상자수,경상자수,부상자수,ECLO
0,ACCIDENT_00000,2019-01-01 00,화요일,맑음,대구광역시 중구 대신동,단일로 - 기타,건조,차대사람,길가장자리구역통행중,안전운전불이행,...,상해없음,보행자,여,70세,중상,0,1,0,0,5
1,ACCIDENT_00001,2019-01-01 00,화요일,흐림,대구광역시 달서구 감삼동,단일로 - 기타,건조,차대사람,보도통행중,기타,...,상해없음,보행자,남,61세,경상,0,0,1,0,3
2,ACCIDENT_00002,2019-01-01 01,화요일,맑음,대구광역시 수성구 두산동,단일로 - 기타,건조,차대사람,차도통행중,안전운전불이행,...,상해없음,보행자,남,38세,경상,0,0,1,0,3
3,ACCIDENT_00003,2019-01-01 02,화요일,맑음,대구광역시 북구 복현동,단일로 - 기타,건조,차대차,추돌,안전운전불이행,...,상해없음,승용,남,36세,중상,0,1,0,0,5
4,ACCIDENT_00004,2019-01-01 04,화요일,맑음,대구광역시 동구 신암동,단일로 - 기타,건조,차대차,추돌,안전운전불이행,...,상해없음,승용,남,52세,경상,0,0,1,0,3

In [4]:
print(df_train.shape)
print(df_test.shape)

(39609, 23)
(10963, 8)

In [5]:
print(df_train.columns)
print(df_test.columns)

Index(['ID', '사고일시', '요일', '기상상태', '시군구', '도로형태', '노면상태', '사고유형',
       '사고유형 - 세부분류', '법규위반', '가해운전자 차종', '가해운전자 성별', '가해운전자 연령', '가해운전자 상해정도',
       '피해운전자 차종', '피해운전자 성별', '피해운전자 연령', '피해운전자 상해정도', '사망자수', '중상자수',
       '경상자수', '부상자수', 'ECLO'],
      dtype='object')
Index(['ID', '사고일시', '요일', '기상상태', '시군구', '도로형태', '노면상태', '사고유형'], dtype='object')

In [6]:
df_train.isnull().sum()

ID               0
사고일시             0
요일               0
기상상태             0
시군구              0
도로형태             0
노면상태             0
사고유형             0
사고유형 - 세부분류      0
법규위반             0
가해운전자 차종         0
가해운전자 성별         0
가해운전자 연령         0
가해운전자 상해정도       0
피해운전자 차종       991
피해운전자 성별       991
피해운전자 연령       991
피해운전자 상해정도     991
사망자수             0
중상자수             0
경상자수             0
부상자수             0
ECLO             0
dtype: int64

In [7]:
df_train.loc[:, ['피해운전자 차종', '피해운전자 성별', '피해운전자 연령', '피해운전자 상해정도']]

      피해운전자 차종 피해운전자 성별 피해운전자 연령 피해운전자 상해정도
0          보행자        여      70세         중상
1          보행자        남      61세         경상
2          보행자        남      38세         경상
3           승용        남      36세         중상
4           승용        남      52세         경상
...        ...      ...      ...        ...
39604       이륜        남      28세         경상
39605       승용        남      52세         경상
39606       승용        남      73세         중상
39607       승용        여      57세         경상
39608       승용        남      33세         경상

[39609 rows x 4 columns]

In [8]:
from conf import config

df_train = pd.read_csv(config['input']['train'])
lit = ["사고유형 - 세부분류", "법규위반", "가해운전자 차종", "가해운전자 성별", "가해운전자 연령", "가해운전자 상해정도","피해운전자 차종", "피해운전자 성별", "피해운전자 연령", "피해운전자 상해정도"]

df_train.drop(columns=lit, axis=1, inplace=True)

In [9]:
df_train.head()

,ID,사고일시,요일,기상상태,시군구,도로형태,노면상태,사고유형,사망자수,중상자수,경상자수,부상자수,ECLO
0,ACCIDENT_00000,2019-01-01 00,화요일,맑음,대구광역시 중구 대신동,단일로 - 기타,건조,차대사람,0,1,0,0,5
1,ACCIDENT_00001,2019-01-01 00,화요일,흐림,대구광역시 달서구 감삼동,단일로 - 기타,건조,차대사람,0,0,1,0,3
2,ACCIDENT_00002,2019-01-01 01,화요일,맑음,대구광역시 수성구 두산동,단일로 - 기타,건조,차대사람,0,0,1,0,3
3,ACCIDENT_00003,2019-01-01 02,화요일,맑음,대구광역시 북구 복현동,단일로 - 기타,건조,차대차,0,1,0,0,5
4,ACCIDENT_00004,2019-01-01 04,화요일,맑음,대구광역시 동구 신암동,단일로 - 기타,건조,차대차,0,0,1,0,3

In [10]:
df_train.dtypes

ID      object
사고일시    object
요일      object
기상상태    object
시군구     object
도로형태    object
노면상태    object
사고유형    object
사망자수     int64
중상자수     int64
경상자수     int64
부상자수     int64
ECLO     int64
dtype: object

In [11]:
df_train['날짜'] = df_train['사고일시'].str.split(' ').str[0]
df_train['연'] = df_train['날짜'].str.split('-').str[0]
df_train['월'] = df_train['날짜'].str.split('-').str[1]
df_train['일'] = df_train['날짜'].str.split('-').str[2]
df_train.drop('날짜', axis=1, inplace=True)
df_train['시간'] = df_train['사고일시'].str.split(' ').str[1]
df_train.drop('사고일시', axis=1, inplace=True)

In [12]:
df_train.head()

,ID,요일,기상상태,시군구,도로형태,노면상태,사고유형,사망자수,중상자수,경상자수,부상자수,ECLO,연,월,일,시간
0,ACCIDENT_00000,화요일,맑음,대구광역시 중구 대신동,단일로 - 기타,건조,차대사람,0,1,0,0,5,2019,01,01,00
1,ACCIDENT_00001,화요일,흐림,대구광역시 달서구 감삼동,단일로 - 기타,건조,차대사람,0,0,1,0,3,2019,01,01,00
2,ACCIDENT_00002,화요일,맑음,대구광역시 수성구 두산동,단일로 - 기타,건조,차대사람,0,0,1,0,3,2019,01,01,01
3,ACCIDENT_00003,화요일,맑음,대구광역시 북구 복현동,단일로 - 기타,건조,차대차,0,1,0,0,5,2019,01,01,02
4,ACCIDENT_00004,화요일,맑음,대구광역시 동구 신암동,단일로 - 기타,건조,차대차,0,0,1,0,3,2019,01,01,04

In [13]:
df_train['군'] = df_train['시군구'].str.split(' ').str[1]
df_train['동'] = df_train['시군구'].str.split(' ').str[2]
df_train.drop('시군구', axis=1, inplace=True)
df_train.head()

,ID,요일,기상상태,도로형태,노면상태,사고유형,사망자수,중상자수,경상자수,부상자수,ECLO,연,월,일,시간,군,동
0,ACCIDENT_00000,화요일,맑음,단일로 - 기타,건조,차대사람,0,1,0,0,5,2019,01,01,00,중구,대신동
1,ACCIDENT_00001,화요일,흐림,단일로 - 기타,건조,차대사람,0,0,1,0,3,2019,01,01,00,달서구,감삼동
2,ACCIDENT_00002,화요일,맑음,단일로 - 기타,건조,차대사람,0,0,1,0,3,2019,01,01,01,수성구,두산동
3,ACCIDENT_00003,화요일,맑음,단일로 - 기타,건조,차대차,0,1,0,0,5,2019,01,01,02,북구,복현동
4,ACCIDENT_00004,화요일,맑음,단일로 - 기타,건조,차대차,0,0,1,0,3,2019,01,01,04,동구,신암동

In [14]:
df_train['도로형태'].unique()

array(['단일로 - 기타', '교차로 - 교차로안', '기타 - 기타', '단일로 - 터널', '단일로 - 지하차도(도로)내',
       '단일로 - 교량', '교차로 - 교차로횡단보도내', '주차장 - 주차장', '교차로 - 교차로부근',
       '단일로 - 고가도로위', '미분류 - 미분류'], dtype=object)

In [15]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(df_train['도로형태'])
# print("Original categories:", df_train['도로형태'])
# print("Encoded labels:", encoded_labels)
df_train['도로형태'].unique()

array(['단일로 - 기타', '교차로 - 교차로안', '기타 - 기타', '단일로 - 터널', '단일로 - 지하차도(도로)내',
       '단일로 - 교량', '교차로 - 교차로횡단보도내', '주차장 - 주차장', '교차로 - 교차로부근',
       '단일로 - 고가도로위', '미분류 - 미분류'], dtype=object)

In [16]:
df_train['도로형태'].value_counts()

도로형태
단일로 - 기타           19485
교차로 - 교차로안          9931
교차로 - 교차로부근         5746
기타 - 기타             1986
교차로 - 교차로횡단보도내      1474
단일로 - 지하차도(도로)내      309
주차장 - 주차장            236
단일로 - 교량             232
단일로 - 고가도로위          138
단일로 - 터널              64
미분류 - 미분류              8
Name: count, dtype: int64

In [17]:
df_train.groupby('도로형태')[['사망자수', '중상자수', '경상자수', '부상자수']].agg({
    '사망자수': 'sum',
    '중상자수': 'sum',
    '경상자수': 'sum',
    '부상자수': 'sum'
})

                 사망자수  중상자수   경상자수  부상자수
도로형태
교차로 - 교차로부근        28  1376   6670   773
교차로 - 교차로안         66  2933  11036  1283
교차로 - 교차로횡단보도내     18   585    945   137
기타 - 기타             9   444   1850   215
단일로 - 고가도로위         2    24    207    14
단일로 - 교량            3    48    305    24
단일로 - 기타          178  4849  20719  2501
단일로 - 지하차도(도로)내     1    81    320    39
단일로 - 터널            3    16    102     5
미분류 - 미분류           0     1      8     1
주차장 - 주차장           0    35    223    33

In [18]:
df_train.head()

,ID,요일,기상상태,도로형태,노면상태,사고유형,사망자수,중상자수,경상자수,부상자수,ECLO,연,월,일,시간,군,동
0,ACCIDENT_00000,화요일,맑음,단일로 - 기타,건조,차대사람,0,1,0,0,5,2019,01,01,00,중구,대신동
1,ACCIDENT_00001,화요일,흐림,단일로 - 기타,건조,차대사람,0,0,1,0,3,2019,01,01,00,달서구,감삼동
2,ACCIDENT_00002,화요일,맑음,단일로 - 기타,건조,차대사람,0,0,1,0,3,2019,01,01,01,수성구,두산동
3,ACCIDENT_00003,화요일,맑음,단일로 - 기타,건조,차대차,0,1,0,0,5,2019,01,01,02,북구,복현동
4,ACCIDENT_00004,화요일,맑음,단일로 - 기타,건조,차대차,0,0,1,0,3,2019,01,01,04,동구,신암동

In [19]:
df_train['사고유형'].unique()

array(['차대사람', '차대차', '차량단독'], dtype=object)

In [20]:
df_train['노면상태'].unique()

array(['건조', '젖음/습기', '서리/결빙', '기타', '침수', '적설'], dtype=object)

In [21]:
df_train['도로형태'].unique()

array(['단일로 - 기타', '교차로 - 교차로안', '기타 - 기타', '단일로 - 터널', '단일로 - 지하차도(도로)내',
       '단일로 - 교량', '교차로 - 교차로횡단보도내', '주차장 - 주차장', '교차로 - 교차로부근',
       '단일로 - 고가도로위', '미분류 - 미분류'], dtype=object)

In [22]:
df_train.head()

,ID,요일,기상상태,도로형태,노면상태,사고유형,사망자수,중상자수,경상자수,부상자수,ECLO,연,월,일,시간,군,동
0,ACCIDENT_00000,화요일,맑음,단일로 - 기타,건조,차대사람,0,1,0,0,5,2019,01,01,00,중구,대신동
1,ACCIDENT_00001,화요일,흐림,단일로 - 기타,건조,차대사람,0,0,1,0,3,2019,01,01,00,달서구,감삼동
2,ACCIDENT_00002,화요일,맑음,단일로 - 기타,건조,차대사람,0,0,1,0,3,2019,01,01,01,수성구,두산동
3,ACCIDENT_00003,화요일,맑음,단일로 - 기타,건조,차대차,0,1,0,0,5,2019,01,01,02,북구,복현동
4,ACCIDENT_00004,화요일,맑음,단일로 - 기타,건조,차대차,0,0,1,0,3,2019,01,01,04,동구,신암동

In [23]:
df_train.loc[df_train['도로형태'].str.split('-').str[0] == '단일로', '도로형태-단일로'] = df_train['도로형태'].str.split('-').str[1]

In [24]:
df_train.head()

,ID,요일,기상상태,도로형태,노면상태,사고유형,사망자수,중상자수,경상자수,부상자수,ECLO,연,월,일,시간,군,동,도로형태-단일로
0,ACCIDENT_00000,화요일,맑음,단일로 - 기타,건조,차대사람,0,1,0,0,5,2019,01,01,00,중구,대신동,NaN
1,ACCIDENT_00001,화요일,흐림,단일로 - 기타,건조,차대사람,0,0,1,0,3,2019,01,01,00,달서구,감삼동,NaN
2,ACCIDENT_00002,화요일,맑음,단일로 - 기타,건조,차대사람,0,0,1,0,3,2019,01,01,01,수성구,두산동,NaN
3,ACCIDENT_00003,화요일,맑음,단일로 - 기타,건조,차대차,0,1,0,0,5,2019,01,01,02,북구,복현동,NaN
4,ACCIDENT_00004,화요일,맑음,단일로 - 기타,건조,차대차,0,0,1,0,3,2019,01,01,04,동구,신암동,NaN

In [25]:
if df_train.loc['도로형태'].str.split("-").str[0] == '단일로':
    df_train.loc['도로형태-단일로'].str.split("-").str[1]

KeyError: '도로형태'

In [ ]:
df_train.head()

,ID,사고일시,요일,기상상태,시군구,도로형태,노면상태,사고유형,사고유형 - 세부분류,법규위반,...,가해운전자 상해정도,피해운전자 차종,피해운전자 성별,피해운전자 연령,피해운전자 상해정도,사망자수,중상자수,경상자수,부상자수,ECLO
0,ACCIDENT_00000,2019-01-01 00,화요일,맑음,대구광역시 중구 대신동,단일로 - 기타,건조,차대사람,길가장자리구역통행중,안전운전불이행,...,상해없음,보행자,여,70세,중상,0,1,0,0,5
1,ACCIDENT_00001,2019-01-01 00,화요일,흐림,대구광역시 달서구 감삼동,단일로 - 기타,건조,차대사람,보도통행중,기타,...,상해없음,보행자,남,61세,경상,0,0,1,0,3
2,ACCIDENT_00002,2019-01-01 01,화요일,맑음,대구광역시 수성구 두산동,단일로 - 기타,건조,차대사람,차도통행중,안전운전불이행,...,상해없음,보행자,남,38세,경상,0,0,1,0,3
3,ACCIDENT_00003,2019-01-01 02,화요일,맑음,대구광역시 북구 복현동,단일로 - 기타,건조,차대차,추돌,안전운전불이행,...,상해없음,승용,남,36세,중상,0,1,0,0,5
4,ACCIDENT_00004,2019-01-01 04,화요일,맑음,대구광역시 동구 신암동,단일로 - 기타,건조,차대차,추돌,안전운전불이행,...,상해없음,승용,남,52세,경상,0,0,1,0,3

In [ ]:
df_train.index

RangeIndex(start=0, stop=39609, step=1)

In [ ]:
idx = 'ID'
tgt = 'ECLO'
df_idx = df_train.set_index(idx, drop=True)
df_idx

,사고일시,요일,기상상태,시군구,도로형태,노면상태,사고유형,사고유형 - 세부분류,법규위반,가해운전자 차종,...,가해운전자 상해정도,피해운전자 차종,피해운전자 성별,피해운전자 연령,피해운전자 상해정도,사망자수,중상자수,경상자수,부상자수,ECLO
ID,,,,,,,,,,,,,,,,,,,,,
ACCIDENT_00000,2019-01-01 00,화요일,맑음,대구광역시 중구 대신동,단일로 - 기타,건조,차대사람,길가장자리구역통행중,안전운전불이행,승용,...,상해없음,보행자,여,70세,중상,0,1,0,0,5
ACCIDENT_00001,2019-01-01 00,화요일,흐림,대구광역시 달서구 감삼동,단일로 - 기타,건조,차대사람,보도통행중,기타,승용,...,상해없음,보행자,남,61세,경상,0,0,1,0,3
ACCIDENT_00002,2019-01-01 01,화요일,맑음,대구광역시 수성구 두산동,단일로 - 기타,건조,차대사람,차도통행중,안전운전불이행,승용,...,상해없음,보행자,남,38세,경상,0,0,1,0,3
ACCIDENT_00003,2019-01-01 02,화요일,맑음,대구광역시 북구 복현동,단일로 - 기타,건조,차대차,추돌,안전운전불이행,승용,...,상해없음,승용,남,36세,중상,0,1,0,0,5
ACCIDENT_00004,2019-01-01 04,화요일,맑음,대구광역시 동구 신암동,단일로 - 기타,건조,차대차,추돌,안전운전불이행,승용,...,상해없음,승용,남,52세,경상,0,0,1,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ACCIDENT_39604,2021-12-31 19,금요일,맑음,대구광역시 수성구 수성동3가,교차로 - 교차로안,건조,차대차,측면충돌,신호위반,승용,...,상해없음,이륜,남,28세,경상,0,0,1,0,3
ACCIDENT_39605,2021-12-31 19,금요일,맑음,대구광역시 달서구 상인동,단일로 - 기타,건조,차대차,측면충돌,안전거리미확보,승용,...,상해없음,승용,남,52세,경상,0,0,1,0,3
ACCIDENT_39606,2021-12-31 21,금요일,맑음,대구광역시 달서구 월성동,교차로 - 교차로안,건조,차대차,측면충돌,교차로운행방법위반,승용,...,중상,승용,남,73세,중상,0,2,0,0,10
ACCIDENT_39607,2021-12-31 22,금요일,맑음,대구광역시 달서구 장동,기타 - 기타,건조,차대차,추돌,안전운전불이행,승용,...,상해없음,승용,여,57세,경상,0,0,1,0,3
ACCIDENT_39608,2021-12-31 23,금요일,맑음,대구광역시 서구 비산동,단일로 - 지하차도(도로)내,건조,차대차,측면충돌,안전운전불이행,승용,...,상해없음,승용,남,33세,경상,0,0,2,0,6

In [ ]:
a = pd.read_csv("E:/Clean/Lec/Btcmp/Practice/gitPrac/review/data/prep_train.csv")

In [ ]:
a

,ID,요일,기상상태_기타,기상상태_눈,기상상태_맑음,기상상태_비,기상상태_안개,기상상태_흐림,도로형태_교차로 - 교차로부근,도로형태_교차로 - 교차로안,...,동_학정동,동_향촌동,동_현풍읍,동_호림동,동_호산동,동_화원읍,동_화전동,동_황금동,동_효목동,ECLO
0,ACCIDENT_00000,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5
1,ACCIDENT_00001,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
2,ACCIDENT_00002,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
3,ACCIDENT_00003,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5
4,ACCIDENT_00004,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39604,ACCIDENT_39604,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
39605,ACCIDENT_39605,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
39606,ACCIDENT_39606,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10
39607,ACCIDENT_39607,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
39608,ACCIDENT_39608,1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6

In [ ]:
import torch

In [ ]:
df_x = torch.tensor(pd.read_csv("E:/Clean/Lec/Btcmp/Practice/gitPrac/review/data/prep_train.csv"))

ValueError: could not determine the shape of object type 'DataFrame'

In [28]:
 = df_train["ECLO"]
b.to_csv("../review/data/prep_target.csv")

In [27]:
a

,1,2,3,4,5,6,7,8,9,10,...,39,40,45,47,52,56,57,65,66,74
0,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39604,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39605,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39606,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
39607,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39608,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [37]:
type(b)

pandas.core.series.Series

In [39]:
b.shape

(39609,)

In [40]:
import torch
import pandas as pd
import numpy as np
import torchmetrics
from torch import nn
from torch.utils.data import DataLoader
from tqdm.auto import trange
from torch.utils.data.dataset import TensorDataset

df_x = torch.tensor(pd.read_csv(config['output']['prep_train'], index_col=0).to_numpy(dtype=np.float32))
df_y = torch.tensor(pd.read_csv("../review/data/prep_target.csv").to_numpy(dtype=np.float32))
ds = TensorDataset(df_x, df_y)
dl = DataLoader(ds, batch_size = 32, shuffle = True)

In [41]:
x, y = next(iter(dl))
x.shape, y.shape

(torch.Size([32, 302]), torch.Size([32, 2]))

In [45]:
x[0].shape

torch.Size([302])

In [47]:
y[0].shape

torch.Size([2])